name: Deploy Angular in Firebase

on:
    push:
        branches: 
          - main
          - 'release/**'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [
                        20.x #, 22.x
                    ]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Set Environment Variable
              run: |
                if [[ "${GITHUB_REF#refs/heads/}" =~ ^release.* ]]; then
                    echo "ENVIRONMENT=prod" >> $GITHUB_ENV
                    echo "TARGET=stockwallet" >> $GITHUB_ENV
                else
                    echo "ENVIRONMENT=dev" >> $GITHUB_ENV
                    echo "TARGET=stockwalletang" >> $GITHUB_ENV
                fi

            - name: Install dependencies
              run: npm install

            - name: Set environment variables from GitHub secrets
              run: |
                echo "DEV_FIREBASE_KEY=${{ secrets.DEV_FIREBASE_KEY }}" >> $GITHUB_ENV
                echo "DEV_FIREBASE_AUTH_DOMAIN=${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}" >> $GITHUB_ENV
                echo "DEV_FIREBASE_PROJECT_ID=${{ secrets.DEV_FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
                echo "DEV_FIREBASE_STORAGE_BUCKET=${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}" >> $GITHUB_ENV
                echo "DEV_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
                echo "DEV_FIREBASE_APP_ID=${{ secrets.DEV_FIREBASE_APP_ID }}" >> $GITHUB_ENV
                echo "DEV_FIREBASE_MEASUREMENT_ID=${{ secrets.DEV_FIREBASE_MEASUREMENT_ID }}" >> $GITHUB_ENV
                echo "DEV_RAPID_API_URL=${{ secrets.DEV_RAPID_API_URL }}" >> $GITHUB_ENV
                echo "DEV_RAPID_API_HOST_FIELD=${{ secrets.DEV_RAPID_API_HOST_FIELD }}" >> $GITHUB_ENV
                echo "DEV_RAPID_API_HOST=${{ secrets.DEV_RAPID_API_HOST }}" >> $GITHUB_ENV
                echo "DEV_RAPID_API_KEY_FIELD=${{ secrets.DEV_RAPID_API_KEY_FIELD }}" >> $GITHUB_ENV
                echo "DEV_RAPID_API_KEY=${{ secrets.DEV_RAPID_API_KEY }}" >> $GITHUB_ENV
                echo "DEV_LOGOS_URL=${{ secrets.DEV_LOGOS_URL }}" >> $GITHUB_ENV

            - name: Inject environment variables into environment
              run: |
                mkdir -p src/environments
                echo "" > src/environments/environment.ts
                if [ "$ENVIRONMENT" == "prod" ]; then
                    node ./scripts/set-prod-environment-vars.js
                else
                    node ./scripts/set-environment-vars.js
                fi

            - name: Run lint and build
              run: |
                npm run lint
                if [ "$ENVIRONMENT" == "prod" ]; then
                  npm run build:prod
                else
                  npm run build
                fi

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Deploy to Firebase
              run: |
                echo "STOCKWALLET_FIREBASE_CLIENT_SECRET=${{ secrets.STOCKWALLET_FIREBASE_CLIENT_SECRET }}" >> $GITHUB_ENV
                echo "$STOCKWALLET_FIREBASE_CLIENT_SECRET" | base64 -d > $HOME/firebase_key.json
                echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_key.json" >> $GITHUB_ENV
                firebase deploy --only hosting:$TARGET

