name: Deploy Angular in Firebase

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [
                        18.x #, 20.x, 22.x
                    ]

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm install

            - name: Set environment variables from GitHub secrets
              run: |
                echo "TEST_VAR=${{ secrets.TEST_VAR }}" >> $GITHUB_ENV

            - name: Inject environment variables into environment.js
              run: |
                node ./scripts/set-environment-vars.js

            - name: Run lint and build
              run: |
                  npm run lint
                  npm run build

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Deploy to Firebase
              run: firebase deploy --token "${{ secrets.STOCKWALLET_TOKEN }}"

